#| Rose-Pine theme |#
import = ["~/.config/alacritty/themes/rose-pine.toml"]

[font]
size = 12.5

[font.normal]
family = "CascadiaCode"
style = "Bold"

[font.bold_italic]
style = "Bold Italic"

[font.italic]
style = "Italic"

[scrolling]
history = 200

[window]
opacity = 0.9

[window.padding]
x = 15
y = 15

